Change missing translation check to empty file

diff --git a/.github/workflows/check-i18n.yml b/.github/workflows/check-i18n.yml
--- a/.github/workflows/check-i18n.yml
+++ b/.github/workflows/check-i18n.yml
@@ -43,8 +43,9 @@ jobs:
     - name: Generate Hugo i18n warnings
       run: hugo --printI18nWarnings | grep MISSING_TRANSLATION > /tmp/i18n-warnings.txt || true
 
-    - name: Count Hugo i18n warnings
-      run: if [[ `wc -l /tmp/i18n-warnings.txt` ]]; then cat /tmp/i18n-warnings.txt && exit 1; else echo "No missing translations"; fi
+    # check if file is empty
+    - name: Check for any missing translations from Hugo i18n warnings
+      run: if [[ -s /tmp/i18n-warnings.txt ]]; then cat /tmp/i18n-warnings.txt && exit 1; else echo "No missing translations"; fi
 
 
 
